const constants = {
    ORDERS_SUCCESS:"ORDERS_SUCCESS",
    ORDERS_FAILURE:"ORDERS_FAILURE",

    INVENTORYCOUNT_FAILURE:"INVENTORYCOUNT_FAILURE",
    INVENTORYCOUNT_SUCCESS:"INVENTORYCOUNT_SUCCESS",

    CUSTOMERCOUNT_FAILURE:"CUSTOMERCOUNT_FAILURE",
    CUSTOMERCOUNT_SUCCESS:"CUSTOMERCOUNT_SUCCESS",

    REVENUECOUNT_FAILURE:"REVENUECOUNT_FAILURE",
    REVENUECOUNT_SUCCESS:"REVENUECOUNT_SUCCESS"
}

export default constants;